/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as ChildSafeguardingRouteImport } from './routes/child-safeguarding'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ParentInformationRouteImport } from './routes/parent-information'
import { Route as ParkRouteImport } from './routes/park'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SchoolLifeRouteImport } from './routes/school-life'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as AcademicsJuniorRouteImport } from './routes/academics.junior'
import { Route as AcademicsKindergartenRouteImport } from './routes/academics.kindergarten'
import { Route as AcademicsPrimaryRouteImport } from './routes/academics.primary'
import { Route as AcademicsSeniorRouteImport } from './routes/academics.senior'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafeguardingRoute = ChildSafeguardingRouteImport.update({
  id: '/child-safeguarding',
  path: '/child-safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentInformationRoute = ParentInformationRouteImport.update({
  id: '/parent-information',
  path: '/parent-information',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkRoute = ParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolLifeRoute = SchoolLifeRouteImport.update({
  id: '/school-life',
  path: '/school-life',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/academics/',
  path: '/academics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsJuniorRoute = AcademicsJuniorRouteImport.update({
  id: '/academics/junior',
  path: '/academics/junior',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsKindergartenRoute = AcademicsKindergartenRouteImport.update({
  id: '/academics/kindergarten',
  path: '/academics/kindergarten',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsPrimaryRoute = AcademicsPrimaryRouteImport.update({
  id: '/academics/primary',
  path: '/academics/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSeniorRoute = AcademicsSeniorRouteImport.update({
  id: '/academics/senior',
  path: '/academics/senior',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/boarding': typeof BoardingRoute
  '/child-safeguarding': typeof ChildSafeguardingRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-information': typeof ParentInformationRoute
  '/park': typeof ParkRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/school-life': typeof SchoolLifeRoute
  '/terms': typeof TermsRoute
  '/academics/junior': typeof AcademicsJuniorRoute
  '/academics/kindergarten': typeof AcademicsKindergartenRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/senior': typeof AcademicsSeniorRoute
  '/academics/': typeof AcademicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/boarding': typeof BoardingRoute
  '/child-safeguarding': typeof ChildSafeguardingRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-information': typeof ParentInformationRoute
  '/park': typeof ParkRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/school-life': typeof SchoolLifeRoute
  '/terms': typeof TermsRoute
  '/academics/junior': typeof AcademicsJuniorRoute
  '/academics/kindergarten': typeof AcademicsKindergartenRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/senior': typeof AcademicsSeniorRoute
  '/academics': typeof AcademicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/boarding': typeof BoardingRoute
  '/child-safeguarding': typeof ChildSafeguardingRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-information': typeof ParentInformationRoute
  '/park': typeof ParkRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/school-life': typeof SchoolLifeRoute
  '/terms': typeof TermsRoute
  '/academics/junior': typeof AcademicsJuniorRoute
  '/academics/kindergarten': typeof AcademicsKindergartenRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/senior': typeof AcademicsSeniorRoute
  '/academics/': typeof AcademicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/boarding'
    | '/child-safeguarding'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/parent-information'
    | '/park'
    | '/privacy'
    | '/programs'
    | '/school-life'
    | '/terms'
    | '/academics/junior'
    | '/academics/kindergarten'
    | '/academics/primary'
    | '/academics/senior'
    | '/academics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/boarding'
    | '/child-safeguarding'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/parent-information'
    | '/park'
    | '/privacy'
    | '/programs'
    | '/school-life'
    | '/terms'
    | '/academics/junior'
    | '/academics/kindergarten'
    | '/academics/primary'
    | '/academics/senior'
    | '/academics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/boarding'
    | '/child-safeguarding'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/news'
    | '/parent-information'
    | '/park'
    | '/privacy'
    | '/programs'
    | '/school-life'
    | '/terms'
    | '/academics/junior'
    | '/academics/kindergarten'
    | '/academics/primary'
    | '/academics/senior'
    | '/academics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  BoardingRoute: typeof BoardingRoute
  ChildSafeguardingRoute: typeof ChildSafeguardingRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ParentInformationRoute: typeof ParentInformationRoute
  ParkRoute: typeof ParkRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SchoolLifeRoute: typeof SchoolLifeRoute
  TermsRoute: typeof TermsRoute
  AcademicsJuniorRoute: typeof AcademicsJuniorRoute
  AcademicsKindergartenRoute: typeof AcademicsKindergartenRoute
  AcademicsPrimaryRoute: typeof AcademicsPrimaryRoute
  AcademicsSeniorRoute: typeof AcademicsSeniorRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safeguarding': {
      id: '/child-safeguarding'
      path: '/child-safeguarding'
      fullPath: '/child-safeguarding'
      preLoaderRoute: typeof ChildSafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-information': {
      id: '/parent-information'
      path: '/parent-information'
      fullPath: '/parent-information'
      preLoaderRoute: typeof ParentInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park': {
      id: '/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof ParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-life': {
      id: '/school-life'
      path: '/school-life'
      fullPath: '/school-life'
      preLoaderRoute: typeof SchoolLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/': {
      id: '/academics/'
      path: '/academics'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/junior': {
      id: '/academics/junior'
      path: '/academics/junior'
      fullPath: '/academics/junior'
      preLoaderRoute: typeof AcademicsJuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/kindergarten': {
      id: '/academics/kindergarten'
      path: '/academics/kindergarten'
      fullPath: '/academics/kindergarten'
      preLoaderRoute: typeof AcademicsKindergartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/primary': {
      id: '/academics/primary'
      path: '/academics/primary'
      fullPath: '/academics/primary'
      preLoaderRoute: typeof AcademicsPrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/senior': {
      id: '/academics/senior'
      path: '/academics/senior'
      fullPath: '/academics/senior'
      preLoaderRoute: typeof AcademicsSeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  BoardingRoute: BoardingRoute,
  ChildSafeguardingRoute: ChildSafeguardingRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ParentInformationRoute: ParentInformationRoute,
  ParkRoute: ParkRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SchoolLifeRoute: SchoolLifeRoute,
  TermsRoute: TermsRoute,
  AcademicsJuniorRoute: AcademicsJuniorRoute,
  AcademicsKindergartenRoute: AcademicsKindergartenRoute,
  AcademicsPrimaryRoute: AcademicsPrimaryRoute,
  AcademicsSeniorRoute: AcademicsSeniorRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
